# Generated by Django 5.2.7 on 2025-10-12 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('costCenter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceOfFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestForPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestBy', models.CharField(max_length=500)),
                ('payableTo', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('dateRequested', models.DateField(auto_now_add=True)),
                ('dateNeeded', models.DateField()),
                ('bankName', models.CharField(max_length=200)),
                ('accountName', models.CharField(max_length=500)),
                ('accountNumber', models.CharField(max_length=20)),
                ('swiftCode', models.CharField(blank=True, max_length=20, null=True)),
                ('contactPerson', models.CharField(max_length=500)),
                ('contactNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('termsOfPayment', models.TextField()),
                ('pr', models.CharField(max_length=100)),
                ('po', models.CharField(max_length=100)),
                ('rr', models.CharField(max_length=100)),
                ('tin', models.CharField(max_length=20)),
                ('payeeAddress', models.TextField()),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('serviceFee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('lessEWT', models.DecimalField(decimal_places=2, max_digits=9)),
                ('netTotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfps', to='api.department')),
                ('modeOfPayment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfps', to='api.modeofpayment')),
                ('sourceOfFund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfps', to='api.sourceoffund')),
                ('taxRegistration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfps', to='api.taxregistration')),
                ('transactionType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfps', to='api.transactiontype')),
                ('typeOfBusiness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfps', to='api.typeofbusiness')),
            ],
        ),
    ]
