# Generated by Django 5.2.7 on 2025-10-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department_modeofpayment_sourceoffund_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenarioCode', models.CharField(max_length=50, unique=True)),
                ('scenarioName', models.CharField(max_length=255)),
                ('horizonMonths', models.PositiveIntegerField(default=12)),
                ('assumptions', models.JSONField(default=dict)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='capexBudget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='nerPrgrams',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='programs',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MacroMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('fxRate_PHP_USD', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('inflationPct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wageIndex', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('release_version', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['month'],
                'indexes': [models.Index(fields=['month'], name='api_macromo_month_eba22c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(max_length=80)),
                ('horizon_months', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='DriversMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('approvalLeadTimeDays', models.PositiveIntegerField(blank=True, null=True)),
                ('govFundShare', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('isEmergency', models.BooleanField(default=False)),
                ('mopBankTransferPct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month_idx', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='api.department')),
            ],
            options={
                'ordering': ['department', 'month'],
                'indexes': [models.Index(fields=['month'], name='api_drivers_month_abb68d_idx'), models.Index(fields=['department', 'month'], name='api_drivers_departm_55fb05_idx'), models.Index(fields=['month_idx'], name='api_drivers_month_i_0ef01f_idx')],
                'unique_together': {('department', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('p10', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('p50', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('p90', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mean', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('level', models.CharField(default='department', max_length=40)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_results', to='api.department')),
                ('transactionType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_results', to='api.transactiontype')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.forecastrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'month'], name='api_forecas_run_id_5ecfc3_idx'), models.Index(fields=['department', 'month'], name='api_forecas_departm_355548_idx')],
                'unique_together': {('run', 'month', 'department', 'transactionType')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioDeptFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_factors', to='api.scenario')),
            ],
            options={
                'unique_together': {('scenario', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioTxnFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txn_factors', to='api.scenario')),
                ('transactionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactiontype')),
            ],
            options={
                'unique_together': {('scenario', 'transactionType')},
            },
        ),
    ]
