# Generated by Django 5.2.7 on 2025-10-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scenario_department_capexbudget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversmonthly',
            name='activeProg_lab_dept',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driversmonthly',
            name='capexBudget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='driversmonthly',
            name='enrolled_FTE_dept',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driversmonthly',
            name='programLaunches_dept',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
