# Generated by Django 5.2.7 on 2025-10-21 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_driversmonthly_activeprog_lab_dept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='nerPrgrams',
        ),
        migrations.AddField(
            model_name='driversmonthly',
            name='totalNet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='driversmonthly',
            name='enrolled_FTE_dept',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driversmonthly',
            name='govFundShare',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='0–1 ratio', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='driversmonthly',
            name='month_idx',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driversmonthly',
            name='mopBankTransferPct',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0–100%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
