# Generated by Django 5.2.7 on 2025-10-21 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_department_nerprgrams_driversmonthly_totalnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversmonthly',
            name='macro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='api.macromonthly'),
        ),
    ]
