# Generated by Django 5.2.7 on 2025-10-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_driversmonthly_macro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macromonthly',
            name='release_version',
        ),
        migrations.RemoveField(
            model_name='macromonthly',
            name='source',
        ),
    ]
