# Generated by Django 5.2.7 on 2025-10-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_macromonthly_release_version_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driversmonthly',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='macromonthly',
            name='month',
            field=models.DateField(),
        ),
    ]
