# Generated by Django 5.2.7 on 2025-10-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_driversmonthly_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestforpayment',
            old_name='requestBy',
            new_name='requestedBy',
        ),
        migrations.AlterField(
            model_name='requestforpayment',
            name='po',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestforpayment',
            name='pr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestforpayment',
            name='rr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
